### ISSUE TITLE
Goroutine leaks

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixcube#135]
```
 leak.go:138: Leaked goroutine: goroutine 11980 [select]:
        github.com/matrixorigin/matrixcube/components/prophet/cluster.(*RaftCluster).runBackgroundJobs(0x14000cf0e00, 0x2540be400)
        	/Users/lni/src/matrixcube/components/prophet/cluster/cluster.go:239 +0xfc
        created by github.com/matrixorigin/matrixcube/components/prophet/cluster.(*RaftCluster).Start
        	/Users/lni/src/matrixcube/components/prophet/cluster/cluster.go:190 +0x510
    leak.go:138: Leaked goroutine: goroutine 11984 [chan receive]:
        github.com/matrixorigin/matrixcube/components/prophet.(*watcherNotifier).start.func1(0x14006e6a510)
        	/Users/lni/src/matrixcube/components/prophet/prophet_watcher.go:113 +0x8c
        created by github.com/matrixorigin/matrixcube/components/prophet.(*watcherNotifier).start
        	/Users/lni/src/matrixcube/components/prophet/prophet_watcher.go:103 +0x3c
    leak.go:138: Leaked goroutine: goroutine 12279 [select]:
        github.com/matrixorigin/matrixcube/components/prophet.StartMonitor({0x101bf3950, 0x14000040110}, 0x101bb3f78, 0x101bb0b38)
        	/Users/lni/src/matrixcube/components/prophet/systime_mon.go:30 +0x170
        created by github.com/matrixorigin/matrixcube/components/prophet.(*defaultProphet).startSystemMonitor
        	/Users/lni/src/matrixcube/components/prophet/prophet.go:281 +0x5c
    leak.go:138: Leaked goroutine: goroutine 12280 [chan send]:
        github.com/fagongzi/goetty.(*server).Start.func1(0x14006b810e0, 0x14003034540)
        	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/application.go:110 +0x4c
        created by github.com/fagongzi/goetty.(*server).Start
        	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/application.go:109 +0x1a4
    leak.go:138: Leaked goroutine: goroutine 12317 [chan send]:
        github.com/fagongzi/goetty.(*server).Start.func1(0x14005ae3380, 0x140023931c0)
        	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/application.go:110 +0x4c
        created by github.com/fagongzi/goetty.(*server).Start
        	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/application.go:109 +0x1a4
    leak.go:138: Leaked goroutine: goroutine 12320 [chan send]:
        github.com/fagongzi/goetty.(*server).Start.func1(0x14005ae3500, 0x140005d3280)
```

```
    leak.go:138: Leaked goroutine: goroutine 11648 [chan receive]:
        github.com/matrixorigin/matrixcube/components/prophet.(*watcherNotifier).start.func1(0x14006d0aa50)
        	/Users/lni/src/matrixcube/components/prophet/prophet_watcher.go:113 +0x8c
        created by github.com/matrixorigin/matrixcube/components/prophet.(*watcherNotifier).start
        	/Users/lni/src/matrixcube/components/prophet/prophet_watcher.go:103 +0x3c
    leak.go:138: Leaked goroutine: goroutine 11916 [select]:
        github.com/matrixorigin/matrixcube/components/prophet/cluster.(*RaftCluster).runBackgroundJobs(0x14005abb000, 0x2540be400)
        	/Users/lni/src/matrixcube/components/prophet/cluster/cluster.go:239 +0xfc
        created by github.com/matrixorigin/matrixcube/components/prophet/cluster.(*RaftCluster).Start
        	/Users/lni/src/matrixcube/components/prophet/cluster/cluster.go:190 +0x510
    leak.go:138: Leaked goroutine: goroutine 11926 [select]:
        github.com/matrixorigin/matrixcube/components/prophet.StartMonitor({0x101bf3950, 0x14000040110}, 0x101bb3f78, 0x101bb0b38)
        	/Users/lni/src/matrixcube/components/prophet/systime_mon.go:30 +0x170
        created by github.com/matrixorigin/matrixcube/components/prophet.(*defaultProphet).startSystemMonitor
        	/Users/lni/src/matrixcube/components/prophet/prophet.go:281 +0x5c
    leak.go:138: Leaked goroutine: goroutine 11927 [chan send]:
        github.com/fagongzi/goetty.(*server).Start.func1(0x14006e81b60, 0x1400420c740)
        	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/application.go:110 +0x4c
        created by github.com/fagongzi/goetty.(*server).Start
```

```
leak.go:138: Leaked goroutine: goroutine 10018 [chan send]:
        github.com/fagongzi/goetty.(*server).Start.func1(0x140002b53e0, 0x14000d82480)
        	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/application.go:110 +0x4c
        created by github.com/fagongzi/goetty.(*server).Start
        	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/application.go:109 +0x1a4
    leak.go:138: Leaked goroutine: goroutine 10025 [IO wait]:
        internal/poll.runtime_pollWait(0x12a2b7cb8, 0x72)
        	/usr/local/go/src/runtime/netpoll.go:229 +0xa4
        internal/poll.(*pollDesc).wait(0x140002cdc18, 0x72, 0x0)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x38
        internal/poll.(*pollDesc).waitRead(...)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
        internal/poll.(*FD).Read(0x140002cdc00, {0x140005e9000, 0x1000, 0x1000})
        	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x1dc
        net.(*netFD).Read(0x140002cdc00, {0x140005e9000, 0x1000, 0x1000})
        	/usr/local/go/src/net/fd_posix.go:56 +0x44
        net.(*conn).Read(0x140002809f8, {0x140005e9000, 0x1000, 0x1000})
        	/usr/local/go/src/net/net.go:183 +0x4c
        go.etcd.io/etcd/pkg/transport.timeoutConn.Read({{0x101c09340, 0x140002809f8}, 0x12a05f200, 0x12a05f200}, {0x140005e9000, 0x1000, 0x1000})
        	/Users/lni/go/pkg/mod/github.com/deepfabric/etcd@v1.4.15/pkg/transport/timeout_conn.go:43 +0xa0
        github.com/soheilhy/cmux.(*bufferedReader).Read(0x14001a7f2e0, {0x140005e9000, 0x1000, 0x1000})
        	/Users/lni/go/pkg/mod/github.com/soheilhy/cmux@v0.1.4/buffer.go:53 +0x160
        github.com/soheilhy/cmux.(*MuxConn).Read(0x14001a7f2d0, {0x140005e9000, 0x1000, 0x1000})
        	/Users/lni/go/pkg/mod/github.com/soheilhy/cmux@v0.1.4/cmux.go:260 +0x48
        net/http.(*connReader).Read(0x140055e8bd0, {0x140005e9000, 0x1000, 0x1000})
        	/usr/local/go/src/net/http/server.go:780 +0x260
```

there are probably more goroutine leaks

**Comment by lni** [comment]
resolved in the main branch.
