### ISSUE TITLE
Slice bounds out of range in goetty

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixcube#140]
the following crash happened when running `make race-test`, as the go test is executed without -v, no idea what particular test caused the crash. 

```
2021/08/19 15:00:22.964302 [error] prophet: session 3[] read failed with read tcp 127.0.0.1:30000->127.0.0.1:54425: use of closed network connection
2021/08/19 15:00:22.964324 [error] prophet: client read resp from leader 127.0.0.1:30000 failed with EOF
panic: runtime error: slice bounds out of range [:256] with capacity 0

goroutine 16761 [running]:
github.com/fagongzi/goetty/buf.(*SyncPool).Alloc(0xc0004b97c0, 0x100)
	/Users/lni/src/matrixcube/vendor/github.com/fagongzi/goetty/buf/mem_pool.go:56 +0x1c8
github.com/fagongzi/goetty/buf.(*ByteBuf).Clear(0xc006736b40)
	/Users/lni/src/matrixcube/vendor/github.com/fagongzi/goetty/buf/buf.go:203 +0x11c
github.com/fagongzi/goetty.(*baseIO).reset(0xc008397900)
	/Users/lni/src/matrixcube/vendor/github.com/fagongzi/goetty/session.go:364 +0xb0
github.com/fagongzi/goetty.(*baseIO).Close(0xc008397900)
	/Users/lni/src/matrixcube/vendor/github.com/fagongzi/goetty/session.go:163 +0x13c
github.com/matrixorigin/matrixcube/components/prophet.(*asyncClient).resetLeaderConn(0xc0034bf8c0)
	/Users/lni/src/matrixcube/components/prophet/client.go:678 +0x58
github.com/matrixorigin/matrixcube/components/prophet.(*asyncClient).writeLoop(0xc0034bf8c0)
	/Users/lni/src/matrixcube/components/prophet/client.go:595 +0x138
created by github.com/matrixorigin/matrixcube/components/prophet.(*asyncClient).start
	/Users/lni/src/matrixcube/components/prophet/client.go:512 +0x68
FAIL	github.com/matrixorigin/matrixcube/raftstore	159.528s
FAIL
```

**Comment by lni** [comment]
@w-zr had this issue when running tests.

**Comment by zhangxu19830126** [comment]
Processing has not yet started, is solving #133

**Comment by lni** [comment]
Couldn't reproduce in the last several days.
