### ISSUE TITLE
SIGSEGV in tests

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixcube#191]
#### Can be reproduced ?

yes.

#### Steps:

run make test on mac.

#### Expected behavior:

pass all tests

#### Actual behavior:

```
2021/08/25 18:37:41.731807 [info] [raftstore]: store 1003 pd stopped
2021/08/25 18:37:41.731810 [info] [raftstore]: store 1003 all shards stopped
2021/08/25 18:37:41.731816 [info] [raftstore]: store 1003 all snapshot manager stopped
2021/08/25 18:37:41.731820 [info] [raftstore]: router event loop task stopped
2021/08/25 18:37:41.731824 [info] [raftstore]: handle resource heartbeat resp task stopped
2021/08/25 18:37:41.731825 [info] [raftstore]: raft worker worker 0/0 exit
2021/08/25 18:37:41.731827 [info] [raftstore]: timer based tasks stopped
2021/08/25 18:37:41.731830 [info] [raftstore]: store 1003 task runner stopped
2021/08/25 18:37:41.731864 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731867 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731869 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731871 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731875 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731877 [info] [transport]: transfer stopped
2021/08/25 18:37:41.731878 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731878 [info] [raftstore]: store 1003 transport stopped
2021/08/25 18:37:41.731886 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731888 [info] [transport]: send snapshot worker stopped
2021/08/25 18:37:41.731889 [info] [transport]: send raft worker stopped
2021/08/25 18:37:41.731907 [error] [transport]: session 3[127.0.0.1:64156] read failed with read tcp 127.0.0.1:10002->127.0.0.1:64156: use of closed network connection
2021/08/25 18:37:41.731907 [error] [transport]: session 2[127.0.0.1:64155] read failed with read tcp 127.0.0.1:10002->127.0.0.1:64155: use of closed network connection
2021/08/25 18:37:41.731908 [info] [raftstore]: store 1003 rpc stopped
--- FAIL: TestShardPool (19.24s)
2021/08/25 18:37:41.731908 [error] [transport]: session 1[127.0.0.1:64152] read failed with read tcp 127.0.0.1:10002->127.0.0.1:64152: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58 pc=0x10147d8e8]

goroutine 7584 [running]:
testing.tRunner.func1.2({0x101a43020, 0x1026480c0})
  /usr/local/go/src/testing/testing.go:1209 +0x258
testing.tRunner.func1(0x14001e316c0)
  /usr/local/go/src/testing/testing.go:1212 +0x284
panic({0x101a43020, 0x1026480c0})
  /usr/local/go/src/runtime/panic.go:1038 +0x21c
github.com/matrixorigin/matrixcube/components/prophet/core.(*CachedResource).Clone(0x0, {0x1400286f9f0, 0x1, 0x1})
  /Users/lni/src/matrixcube/components/prophet/core/resource.go:127 +0x28
github.com/matrixorigin/matrixcube/raftstore.TestShardPool.func2(0x0)
  /Users/lni/src/matrixcube/raftstore/store_shards_pool_test.go:88 +0x60
github.com/matrixorigin/matrixcube/raftstore.(*testResourcesAware).GetResource(0x1400023cde0, 0x3ed)
  /Users/lni/src/matrixcube/raftstore/store_shards_pool_test.go:34 +0x58
github.com/matrixorigin/matrixcube/raftstore.(*dynamicShardsPool).gcAllocating(0x14000b4b110, {0x12a4b1028, 0x140029c5dc0}, {0x101c27668, 0x1400023cde0})
  /Users/lni/src/matrixcube/raftstore/store_shards_pool.go:359 +0x498
github.com/matrixorigin/matrixcube/raftstore.TestShardPool(0x14001e316c0)
  /Users/lni/src/matrixcube/raftstore/store_shards_pool_test.go:93 +0xc10
testing.tRunner(0x14001e316c0, 0x101bf7008)
  /usr/local/go/src/testing/testing.go:1259 +0x104
created by testing.(*T).Run
  /usr/local/go/src/testing/testing.go:1306 +0x328
FAIL  github.com/matrixorigin/matrixcube/raftstore  85.546s
FAIL
```

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93): head of master
- Hardware parameters:
- OS type: mac
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
Fix by #193
