### ISSUE TITLE
panic: index out of range [18446744073709551615] with length 1

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixcube#209]
#### Can be reproduced ?
Yes

#### Steps:
for i in {1..500}
do
    go test -timeout 60s -count 1  -run ^TestShardPool$ github.com/matrixorigin/matrixcube/raftstore > 2.log
    v=`tail -n 1 2.log | awk {'print $1'}`
    if [ "$v" != "ok" ]
    then
        echo "$i: error"
        exit
    else
        echo "$i: ok"
    fi
done

#### Expected behavior:
PAAS

#### Actual behavior:
500 times failed once

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
2021/08/29 18:17:29.004403 [info] [raftstore]: shard 21 peer 24 added, epoch {ConfVer:3 Version:0 XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}, peers [{ID:22 ContainerID:7 Role:Voter XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0} {ID:23 ContainerID:5 Role:Voter XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0} {ID:24 ContainerID:1 Role:Voter XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}], raft worker 0, apply worker apply-0-0
{"level":"info","ts":"2021-08-29T18:17:29.004+0800","caller":"etcdserver/zap_raft.go:77","msg":"18 [logterm: 5, index: 5, vote: 0] cast MsgPreVote for 16 [logterm: 5, index: 5] at term 5"}
2021/08/29 18:17:29.004392 [error] [transport]: goetty: connection painc runtime error: index out of range [18446744073709551615] with length 1, stack:
goroutine 845 [running]:
github.com/fagongzi/goetty.(*server).doStart.func1.1(0xc00022f780)
	/root/projects/matrixcube/vendor/github.com/fagongzi/goetty/application.go:237 +0xa5
panic(0x1d9ba20, 0xc0017c04f8)
	/opt/lib/go/src/runtime/panic.go:965 +0x1b9
github.com/matrixorigin/matrixcube/raftstore.(*workReady).notify(0xc00052e160, 0x0, 0xffffffffffffffff)
	/root/projects/matrixcube/raftstore/store_ready.go:41 +0x74
github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).notifyWorker(...)
	/root/projects/matrixcube/raftstore/peer_replica.go:376
github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).addEvent(0xc002cc6a00, 0xc000b15ad0, 0x1, 0x1)
	/root/projects/matrixcube/raftstore/peer_event_loop.go:83 +0xaa
github.com/matrixorigin/matrixcube/raftstore.(*peerReplica).step(0xc002cc6a00, 0x11, 0x18, 0x16, 0x6, 0x5, 0x5, 0x0, 0x0, 0x0, ...)
	/root/projects/matrixcube/raftstore/peer_event_loop.go:106 +0x198
github.com/matrixorigin/matrixcube/raftstore.(*store).onRaftMessage(0xc00000c5a0, 0xc000499d40)
	/root/projects/matrixcube/raftstore/store_handler.go:125 +0x218
github.com/matrixorigin/matrixcube/raftstore.(*store).handle(0xc00000c5a0, 0x1e3dba0, 0xc000499d40)
	/root/projects/matrixcube/raftstore/store_handler.go:80 +0x87
github.com/matrixorigin/matrixcube/transport.(*defaultTransport).onMessage(...)
	/root/projects/matrixcube/transport/transport.go:178
github.com/fagongzi/goetty.(*server).doConnection(0xc00022f780, 0x209cb08, 0xc00034f040, 0xc0036c2ac0, 0x2062901)
	/root/projects/matrixcube/vendor/github.com/fagongzi/goetty/application.go:279 +0x375
github.com/fagongzi/goetty.(*server).doStart.func1(0xc00022f780, 0x209cb08, 0xc00034f040)
	/root/projects/matrixcube/vendor/github.com/fagongzi/goetty/application.go:248 +0x93
created by github.com/fagongzi/goetty.(*server).doStart
	/root/projects/matrixcube/vendor/github.com/fagongzi/goetty/application.go:232 +0x1d3
