### ISSUE TITLE
panic when stop the raftstore

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixcube#214]
#### Can be reproduced ?
Yes

#### Steps:
Run `make test` many times

#### Expected behavior:
PAAS

#### Actual behavior:
panic

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
2021/08/31 23:43:38.226506 [info] [raftstore]: store 1 begin to stop
2021/08/31 23:43:38.226758 [error] prophet: client read resp from leader 127.0.0.1:30000 failed with read tcp 127.0.0.1:62413->127.0.0.1:30000: use of closed network connection
2021/08/31 23:43:38.226767 [error] prophet: client read loop stopped
2021/08/31 23:43:38.226826 [error] prophet: session 9[127.0.0.1:62452] read failed with read tcp 127.0.0.1:30000->127.0.0.1:62452: use of closed network connection
2021/08/31 23:43:38.226880 [error] prophet: watcher read events failed with EOF
2021/08/31 23:43:38.226888 [error] prophet: session 4[127.0.0.1:62412] read failed with read tcp 127.0.0.1:30000->127.0.0.1:62412: use of closed network connection
2021/08/31 23:43:38.226889 [error] prophet: reset watcher conn failed with <nil>, retry later
2021/08/31 23:43:38.226939 [error] prophet: session 7[127.0.0.1:62416] read failed with read tcp 127.0.0.1:30000->127.0.0.1:62416: use of closed network connection
2021/08/31 23:43:38.226959 [error] prophet: watcher read events failed with EOF
2021/08/31 23:43:38.226966 [error] prophet: reset watcher conn failed with <nil>, retry later
2021/08/31 23:43:38.226978 [error] prophet: client read resp from leader 127.0.0.1:30000 failed with EOF
2021/08/31 23:43:38.227011 [error] prophet: session 8[127.0.0.1:62451] read failed with read tcp 127.0.0.1:30000->127.0.0.1:62451: use of closed network connection
2021/08/31 23:43:38.227024 [info] prophet: client start init connection to leader 127.0.0.1:30000
panic: runtime error: index out of range [0] with length 0

goroutine 21261 [running]:
github.com/fagongzi/goetty/buf.Int2BytesTo(...)
	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/buf/buf.go:65
github.com/fagongzi/goetty/codec/length.(*lengthCodec).Encode(0x14008139500, {0x103d907a0, 0x140015d8d80}, 0x140081db4f0)
	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/codec/length/codec_length_field.go:89 +0x158
github.com/fagongzi/goetty.(*baseIO).write(0x14007d314a0, {0x103d907a0, 0x140015d8d80}, 0x0)
	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/session.go:298 +0x70
github.com/fagongzi/goetty.(*baseIO).writeLoop(0x14007d314a0, {0x103dfc278, 0x14004ce3b00})
	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/session.go:329 +0x150
created by github.com/fagongzi/goetty.(*baseIO).initConn
	/Users/lni/go/pkg/mod/github.com/fagongzi/goetty@v1.8.0/session.go:383 +0x218
FAIL	github.com/matrixorigin/matrixcube/raftstore	176.267s
