### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by zhangxu19830126** [matrixorigin/matrixcube#216]
#### Can be reproduced ?
Yes

#### Steps:
Run `make test` many times

#### Expected behavior:
PAAS

#### Actual behavior:
Panic

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
panic: send on closed channel

goroutine 1091 [running]:
github.com/matrixorigin/matrixcube/components/prophet.(*asyncClient).do(0x14000d30a50, 0x14002705100)
	/Users/lni/src/ddd/matrixcube/components/prophet/client.go:551 +0x190
github.com/matrixorigin/matrixcube/components/prophet.(*asyncClient).syncDo(0x14000d30a50, 0x14002698800)
	/Users/lni/src/ddd/matrixcube/components/prophet/client.go:524 +0xbc
github.com/matrixorigin/matrixcube/components/prophet.(*asyncClient).ContainerHeartbeat(0x14000d30a50, {{0x5, 0x6130a6d0, 0x140026e6570, 0x731ba15000, 0x577cffd000, 0x1b9ea18000, 0x0, 0x2, 0x0, ...}, ...})
	/Users/lni/src/ddd/matrixcube/components/prophet/client.go:180 +0xd0
github.com/matrixorigin/matrixcube/raftstore.(*store).doStoreHeartbeat(0x140002f63c0, {0xc0444795341ddf88, 0x3aa4843bf, 0x103f15820})
	/Users/lni/src/ddd/matrixcube/raftstore/prophet_adapter.go:350 +0xb84
github.com/matrixorigin/matrixcube/raftstore.(*store).startTimerTasks.func1({0x1034dffd8, 0x14000506cc0})
	/Users/lni/src/ddd/matrixcube/raftstore/store.go:559 +0x2e8
github.com/fagongzi/util/task.(*Runner).RunCancelableTask.func1(0x140002cc230, 0x140000bf920, {0x1034dffd8, 0x14000506cc0})
	/Users/lni/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210409031311-a10fdf8fbd7a/task/task.go:350 +0x88
created by github.com/fagongzi/util/task.(*Runner).RunCancelableTask
	/Users/lni/go/pkg/mod/github.com/fagongzi/util@v0.0.0-20210409031311-a10fdf8fbd7a/task/task.go:345 +0x148
FAIL	github.com/matrixorigin/matrixcube/raftstore	17.178s
FAIL
make: *** [test] Error 1
